title:              Тихое место
email:              ypermitin@yandex.ru
description:        Где делают то, что интересно
author:             Permitin Yuriy
baseurl:            "/"
url:                "https://ypermitin.github.io"

# Social Profiles
twitter_username:
github_username:    YPermitin
facebook_username:
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-38629049-5 # out your google-analytics code

# Build settings
highlighter:        rouge
markdown:           kramdown
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  extensions: fenced_code_blocks
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
